class Options:
    def __init__(self, model_path =''):

        self.dataroot=None
        self.batch_size=1
        self.loadSize=512
        self.input_nc=3
        self.fineSize=512
        self.output_nc=1
        self.ngf=64
        self.ndf=64
        self.netD='basic'
        self.netG='unet_256'
        self.nnG=9
        self.n_layers_D=3
        self.gpu_ids=[]
        self.name='formal_author'
        self.dataset_mode='single'
        self.model='test'
        self.use_local=True
        self.comb_op=1
        self.lm_dir='dataset/landmark/ALL'
        self.bg_dir='dataset/mask/ALL'
        self.soft_border=0
        self.EYE_H=40
        self.EYE_W=56
        self.NOSE_H=48
        self.NOSE_W=48
        self.MOUTH_H=40
        self.MOUTH_W=64
        self.which_direction='AtoB'
        self.num_threads=1
        self.checkpoints_dir='./checkpoints'
        self.auxiliary_root='auxiliary'
        self.norm='batch'
        self.serial_batches=True
        self.display_winsize=256
        self.display_id=-1
        self.display_server='http://localhost'
        self.display_env='main'
        self.display_port=8097
        self.no_dropout=False
        self.max_dataset_size=float('inf')
        self.resize_or_crop='resize_and_crop'
        self.no_flip=True
        self.init_type='normal'
        self.init_gain=0.02
        self.verbose=False
        self.suffix=''
        self.ntest=float('inf')
        self.results_dir='./results/'
        self.aspect_ratio=1.0
        self.phase='test'
        self.which_epoch='300'
        self.how_many=70
        self.save2=False
        self.isTrain=False
        self.model_path=model_path


        # self.dataroot = False
        # self.ntest = float("inf")
        # self.results_dir = './results'
        # self.aspect_ratio = 1.0
        # self.phase = 'test'
        # self.which_epoch = 300
        # self.how_many=70
        # self.save2 = True
        # self.isTrain = False

        # self.batch_size = int(1)
        # self.loadSize= 512
        # self.input_nc = 3
        # self.output_nc = 1
        # self.fineSize = 512
        # self.ngf = 64
        # self.ndf = 64
        # self.netD = 'basic'
        # self.netG = 'unet_256'
        # self.nnG = 9
        # self.n_layers_D = 3
        # self.gpu_ids = []#'-1'
        # self.name ='formal_author'
        # self.dataset_mode = 'single'
        # self.model = 'test'
        # self.use_local = True
        # self.comb_op=1
        # self.lm_dir='dataset/landmark/ALL'
        # self.bg_dir='dataset/mask/ALL'
        # self.soft_border=0
        # self.EYE_H=40
        # self.EYE_W=56
        # self.NOSE_H=48
        # self.NOSE_W=48
        # self.MOUTH_H=40
        # self.MOUTH_W=64
        # self.which_direction='AtoB'
        # self.num_threads=1
        # self.checkpoints_dir='./checkpoints'
        # self.auxiliary_root='auxiliary'
        # self.norm='batch'
        # self.serial_batches=True
        # self.display_winsize=256
        # self.display_id=-1
        # self.display_server="http://localhost"
        # self.display_env='main'
        # self.display_port=8097
        # self.no_dropout=True
        # self.max_dataset_size=float("inf")
        # self.resize_or_crop='resize_and_crop'
        # self.no_flip=True
        # self.init_type='normal'
        # self.init_gain=0.02
        # self.verbose=True
        # self.suffix=''
        # self.initialized = True
        # self.model_path = model_path
        